# Generated by Django 5.1.4 on 2025-01-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingridient',
            name='description',
        ),
        migrations.AddField(
            model_name='measurement',
            name='abbreviaion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Recipe_nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('nutrition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.nutrition')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.recipe')),
            ],
        ),
    ]
