# Generated by Django 5.1.4 on 2025-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_nutrition_remove_ingridient_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
