# Generated by Django 5.1.4 on 2025-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_measurement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
