# Generated by Django 5.1.4 on 2025-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_measurement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='step',
            field=models.IntegerField(null=True),
        ),
    ]
