# Generated by Django 5.1.4 on 2025-01-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_instruction_appliance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='position',
        ),
    ]
