# Generated by Django 5.1.4 on 2025-01-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_instruction_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='appliance',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='temperatureF',
        ),
    ]
