# Generated by Django 5.1.4 on 2025-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_root_tags_parent_tags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_tags',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='root_tags',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
